/*
 * AKEYLESS Proxy API
 *
 * RESTFull API for interacting with AKEYLESS Proxy Vault
 *
 * API version: 0.1.1
 * Contact: refael@akeyless.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package akeyless_proxy_api

// Response with error description
type ErrorReplyObj struct {
	// Internal error code
	Error_ string `json:"error,omitempty"`
	// Error message
	Message string `json:"message,omitempty"`
}
