/*
 * AKEYLESS Proxy API
 *
 * RESTFull API for interacting with AKEYLESS Proxy Vault
 *
 * API version: 0.1.1
 * Contact: refael@akeyless.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package akeyless_proxy_api

// Base response
type ReplyObj struct {
	Command string `json:"command,omitempty"`
	Response string `json:"response,omitempty"`
	Status string `json:"status,omitempty"`
	Token string `json:"token,omitempty"`
}
